"""Tests for the read-only dashboard query layer, HTTP server, and security
properties. All fixtures live in temporary databases — never the production DB.
"""

from __future__ import annotations

import json
import sqlite3
import threading
import urllib.request
from pathlib import Path

import pytest

from hermes_ebtto import dashboard
from hermes_ebtto.dashboard import queries, server
from hermes_ebtto.storage import Store

MIGRATION_1 = (Path(queries.__file__).resolve().parent.parent / "migrations" / "1.sql").read_text(encoding="utf-8")


@pytest.fixture()
def db(tmp_path):
    """A populated temporary EBTTO database built through the real Store.

    Turn ids use the production ``<session>:<task>:<hex>`` shape so the
    session-prefix linkage in ``_succeeded_sql`` is exercised the same way
    the live plugin writes it.
    """
    store = Store(tmp_path)
    from hermes_ebtto import events as ev

    t = ev.Task(task_fingerprint="fp-1", task_family="terminal",
                sanitized_intent="run a command", provider="test", model="test")
    store.record_task(t)
    task_id = t.task_id  # generated by the recorder
    session = "sess-1"

    def turn(tid: str) -> str:
        return f"{session}:{tid}:abcd"

    ok_call = ev.ToolCall(task_id=task_id, turn_id=turn("pre-1"), tool_call_id="call-1",
                          tool_name="terminal",
                          sanitized_args={"cmd": "ls"}, result_status="ok", duration_ms=12)
    store.record_tool_call(ok_call)
    import time as _time
    _time.sleep(0.05)  # ensure created_at ordering for the recovery query
    fail_call = ev.ToolCall(task_id=task_id, turn_id=turn("pre-2"), tool_call_id="call-2",
                            tool_name="terminal",
                            sanitized_args={"cmd": "boom"}, result_status="error",
                            duration_ms=40, error_class="ValueError",
                            error_message="boom happened")
    store.record_tool_call(fail_call)
    _time.sleep(0.05)
    # a later success on the same session = the recovery event
    recover_call = ev.ToolCall(task_id=task_id, turn_id=turn("pre-3"), tool_call_id="call-3",
                               tool_name="terminal",
                               sanitized_args={"cmd": "ls again"}, result_status="ok",
                               duration_ms=8)
    store.record_tool_call(recover_call)

    # outcomes live under the POST-tool writer's own task/turn ids; the
    # session prefix is what links them to the pre-tool rows.
    post_task = "post-task-1"
    o1 = ev.Outcome(task_id=post_task, turn_id=turn(post_task), result="SUCCESS",
                    confidence=0.9, evidence={"tool": "terminal"})
    store.record_outcome(o1)
    o2 = ev.Outcome(task_id=post_task, turn_id=turn(post_task), result="FAILURE",
                    confidence=0.9, evidence={"tool": "terminal"})
    store.record_outcome(o2)

    # qualified strategy (counts above thresholds); record_strategy accepts dicts
    for i in range(6):
        store.record_strategy({
            "strategy_id": "strat-1", "strategy_name": "terminal best practice",
            "strategy_type": "tool_best_practice", "sequence": [{"tool": "terminal"}],
            "evidence_count": i + 1, "success_count": i + 1, "failure_count": 0,
            "context_count": 3, "confidence": 0.9, "status": "validated",
            "task_family": "terminal"})
    store.record_pattern({
        "pattern_id": "pat-1", "pattern_name": "terminal pattern",
        "pattern_type": "tool_best_practice", "evidence_count": 6,
        "success_count": 6, "failure_count": 0, "confidence": 0.9, "status": "validated"})

    # retrieval telemetry (schema v4 table exists after Store init)
    store._execute(
        """INSERT INTO retrieval_guidance_events
           (guidance_id, task_id, task_fingerprint, hook, candidate_count,
            qualified_count, selected_strategy_id, guidance_returned,
            reason_code, created_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        ("g1", task_id, "terminal", "pre_llm_call", 1, 1, "strat-1", 1,
         "guidance_returned", "2026-10-11T00:00:00Z"))
    return tmp_path


@pytest.fixture()
def conn(db):
    c = queries.open_ro(str(db))
    yield c
    c.close()


# --- overview reconciliation -------------------------------------------------

def test_overview_counts_reconcile(conn):
    d = queries.overview(conn, "all")
    assert d["tool_calls"]["total"] == 3
    # session-level success: the fixture session has a SUCCESS outcome
    assert d["tool_calls"]["succeeded"] == 3
    assert d["tool_calls"]["failed"] == 0
    assert d["success_rate"] == 1.0
    assert d["tasks_total"] == 1
    assert d["strategies"]["total"] == 1
    assert d["strategies"]["qualified"] == 1
    assert d["guidance"]["available"] is True
    assert d["guidance"]["delivered"] == 1


def test_overview_window_filters(conn):
    # fixture rows are 'now' → 24h window sees them; a 0-row check via bogus window falls back
    d = queries.overview(conn, "1h")
    assert d["window"] == "1h"


# --- tool calls --------------------------------------------------------------

def test_tool_calls_filters(conn, db):
    all_rows = queries.tool_calls(conn, window="all")
    assert all_rows["total"] == 3
    # session-level success (session has a SUCCESS outcome): all 3 rows match
    ok = queries.tool_calls(conn, status="success", window="all")
    assert ok["total"] == 3
    # a session with NO success outcome -> every row is a failure
    fail = queries.tool_calls(conn, status="failure", window="all")
    assert fail["total"] == 0
    bytool = queries.tool_calls(conn, tool="terminal", window="all")
    assert bytool["total"] == 3
    task_id = queries.tasks(conn, window="all")["rows"][0]["task_id"]
    bytask = queries.tool_calls(conn, task_id=task_id, window="all")
    assert bytask["total"] == 3
    search = queries.tool_calls(conn, search="boom", window="all")
    assert search["total"] == 1
    empty = queries.tool_calls(conn, tool="nope", window="all")
    assert empty["total"] == 0 and empty["rows"] == []


def test_tool_calls_pagination_bounds(conn):
    d = queries.tool_calls(conn, window="all", page=1, page_size=1)
    assert d["page"] == 1 and len(d["rows"]) == 1
    d2 = queries.tool_calls(conn, window="all", page=999, page_size=1)
    assert d2["rows"] == []
    # oversized page_size is clamped, never trusted
    d3 = queries.tool_calls(conn, window="all", page_size="99999")
    assert d3["page_size"] == queries.MAX_PAGE_SIZE


def test_tool_call_detail(conn):
    d = queries.tool_call_detail(conn, "call-1")
    assert d["tool_name"] == "terminal"
    # outcomes/errors/attempts are looked up by the pre-tool writer's own
    # task_id; the fixture records 0 of each under that id (production links
    # them by session prefix instead) — the lookup must still be safe.
    assert isinstance(d["outcomes"], list)
    assert isinstance(d["errors"], list)
    assert len(d["attempts"]) == 3
    assert queries.tool_call_detail(conn, "missing") is None


# --- failures & recovery -----------------------------------------------------

def test_failures_and_recovery(conn, db):
    # every fixture session has a SUCCESS outcome -> 0 session-level failures
    d = queries.failures(conn, window="all")
    assert d["total"] == 0
    assert d["rows"] == []
    assert d["recoveries"] == []


def test_failures_and_recovery_with_real_failure(tmp_path):
    """A session with NO success outcome yields a failure + recovery pair."""
    store = Store(tmp_path)
    from hermes_ebtto import events as ev
    t = ev.Task(task_fingerprint="fp", task_family="terminal")
    store.record_task(t)
    session = "sess-fail"
    store.record_tool_call(ev.ToolCall(
        task_id=t.task_id, turn_id=f"{session}:a:1", tool_call_id="f1",
        tool_name="terminal", result_status="error", error_class="ValueError",
        error_message="boom"))
    import time as _time
    _time.sleep(0.05)
    store.record_tool_call(ev.ToolCall(
        task_id=t.task_id, turn_id=f"{session}:b:2", tool_call_id="f2",
        tool_name="terminal", result_status="ok"))
    # outcome FAILURE only — no SUCCESS in this session
    store.record_outcome(ev.Outcome(
        task_id="post-2", turn_id=f"{session}:post-2:3", result="FAILURE",
        confidence=0.9, evidence={"tool": "terminal"}))
    c = queries.open_ro(str(tmp_path))
    try:
        d = queries.failures(c, window="all")
        assert d["total"] == 1
        assert d["by_class"][0]["cls"] == "ValueError"
        # the later ok call in the same session = recovery
        assert any(r["task_id"] == t.task_id and r["recovered_at"]
                   for r in d["recoveries"])
    finally:
        c.close()


# --- tasks -------------------------------------------------------------------

def test_tasks_and_timeline(conn, db):
    d = queries.tasks(conn, window="all")
    assert d["total"] == 1
    task_id = d["rows"][0]["task_id"]
    tl = queries.task_timeline(conn, task_id)
    assert tl["task"]["task_family"] == "terminal"
    stages = {e["stage"] for e in tl["events"]}
    # pre-tool rows exist under this task_id; outcomes are written under the
    # post-tool writer's own task_id (production links by session prefix), so
    # the timeline correctly shows only the stages actually persisted for it.
    assert "tool_call" in stages
    assert "outcome" not in stages
    assert tl["missing_stages"], "missing stages must be reported honestly"


# --- memory ------------------------------------------------------------------

def test_strategies_filters_and_detail(conn):
    d = queries.strategies(conn)
    assert d["total"] == 1
    assert queries.strategies(conn, status="validated")["total"] == 1
    assert queries.strategies(conn, status="disabled")["total"] == 0
    assert queries.strategies(conn, family="terminal")["total"] == 1
    assert queries.strategies(conn, family="other")["total"] == 0
    det = queries.strategy_detail(conn, "strat-1")
    assert det["strategy_name"] == "terminal best practice"
    assert det["evidence_sample"], "strategy should expose real outcome evidence"
    assert det["guidance_events"][0]["reason_code"] == "guidance_returned"
    assert queries.strategy_detail(conn, "missing") is None


def test_patterns(conn):
    d = queries.patterns(conn)
    assert d["total"] == 1 and d["rows"][0]["pattern_id"] == "pat-1"


# --- guidance audit ----------------------------------------------------------

def test_guidance_events(conn):
    d = queries.guidance_events(conn)
    assert d["available"] is True
    assert d["total"] == 1
    assert queries.guidance_events(conn, reason_code="guidance_returned")["total"] == 1
    assert queries.guidance_events(conn, reason_code="no_candidate")["total"] == 0


def test_guidance_absent_on_pre_v4_db(tmp_path):
    """A v3 database (no retrieval_guidance_events) reports unavailable, not fake rows."""
    con = sqlite3.connect(tmp_path / "legacy.db")
    con.executescript(
        "CREATE TABLE schema_version (version INTEGER PRIMARY KEY, applied_at TEXT);"
        "INSERT INTO schema_version VALUES (3,'x');"
        "CREATE TABLE tasks (id INTEGER PRIMARY KEY, task_id TEXT, task_fingerprint TEXT,"
        " task_family TEXT, sanitized_intent TEXT, workspace_identifier TEXT, profile TEXT,"
        " model TEXT, provider TEXT, created_at TEXT);"
        "CREATE TABLE tool_calls (id INTEGER PRIMARY KEY, tool_call_id TEXT, task_id TEXT,"
        " turn_id TEXT, order_number INT, attempt_number INT, tool_name TEXT, raw_args TEXT,"
        " sanitized_args TEXT, result_status TEXT, duration_ms INT, error_class TEXT,"
        " error_message TEXT, classified INT, classified_class TEXT, classifier_version TEXT,"
        " evidence TEXT, created_at TEXT);"
        "CREATE TABLE outcomes (id INTEGER PRIMARY KEY, outcome_id TEXT, task_id TEXT,"
        " turn_id TEXT, result TEXT, confidence REAL, evidence TEXT, recorded_at TEXT);"
        "CREATE TABLE strategies (id INTEGER PRIMARY KEY, strategy_id TEXT, strategy_name TEXT,"
        " strategy_type TEXT, sequence TEXT, evidence_count INT, success_count INT,"
        " failure_count INT, context_count INT, confidence REAL, last_validated_at TEXT,"
        " last_used_at TEXT, version INT, scope TEXT, status TEXT, created_at TEXT,"
        " task_family TEXT);"
        "CREATE TABLE patterns (id INTEGER PRIMARY KEY, pattern_id TEXT, pattern_name TEXT,"
        " pattern_type TEXT, evidence_count INT, success_count INT, failure_count INT,"
        " confidence REAL, last_validated_at TEXT, status TEXT, created_at TEXT);"
    )
    con.commit(); con.close()
    c = queries.open_ro(str(tmp_path / "legacy.db"))
    try:
        assert queries.has_guidance_telemetry(c) is False
        d = queries.guidance_events(c)
        assert d["available"] is False and d["rows"] == []
        st = queries.system_status(c, str(tmp_path / "legacy.db"))
        assert st["schema_version"] == 3
        assert st["guidance_telemetry"] is False
    finally:
        c.close()


# --- database safety ---------------------------------------------------------

def test_readonly_connection_cannot_write(conn):
    with pytest.raises(sqlite3.OperationalError):
        conn.execute("INSERT INTO tasks (task_id) VALUES ('x')")
    with pytest.raises(sqlite3.OperationalError):
        conn.execute("CREATE TABLE nope (x)")


def test_missing_db_raises_clean_error(tmp_path):
    with pytest.raises(queries.DashboardError, match="not found"):
        queries.open_ro(str(tmp_path / "nonexistent" / "ebtto.db"))


def test_bad_schema_raises_clean_error(tmp_path):
    p = tmp_path / "random.db"
    sqlite3.connect(str(p)).close()
    with pytest.raises(queries.DashboardError, match="incompatible"):
        queries.open_ro(str(p))


def test_dashboard_never_creates_db(tmp_path):
    before = set(p.name for p in tmp_path.iterdir())
    with pytest.raises(queries.DashboardError):
        queries.open_ro(str(tmp_path / "new.db"))
    after = set(p.name for p in tmp_path.iterdir())
    assert before == after, "dashboard must not create a database file"


def test_concurrent_writer_and_reader(tmp_path):
    """WAL: plugin writes while dashboard reads — reader must not block or fail."""
    store = Store(tmp_path)
    stop = threading.Event()
    errors = []

    def writer():
        from hermes_ebtto import events as ev
        i = 0
        while not stop.is_set():
            store.record_tool_call(ev.ToolCall(
                task_id="t", tool_call_id=f"c-{i}", tool_name="terminal",
                result_status="ok", duration_ms=1))
            i += 1
    th = threading.Thread(target=writer); th.start()
    try:
        for _ in range(5):
            c = queries.open_ro(str(tmp_path))
            queries.tool_calls(c, window="all")
            c.close()
    except Exception as e:
        errors.append(e)
    finally:
        stop.set(); th.join()
    assert not errors, f"concurrent reads failed: {errors}"


# --- HTTP server -------------------------------------------------------------

@pytest.fixture()
def http_server(db):
    port = server.find_free_port(18997, tries=5)
    t = threading.Thread(
        target=server.serve,
        kwargs={"port": port, "db_path": str(db), "open_browser": False},
        daemon=True)
    t.start()
    import time
    for _ in range(50):
        try:
            urllib.request.urlopen(f"http://127.0.0.1:{port}/api/system", timeout=1).read()
            break
        except Exception:
            time.sleep(0.1)
    yield port
    # daemon thread dies with the test process


def _get(port, path):
    with urllib.request.urlopen(f"http://127.0.0.1:{port}{path}", timeout=5) as r:
        return r.status, r.headers.get("Content-Type", ""), r.read()


def test_server_api_endpoints(http_server):
    for path in ("/api/overview", "/api/tool_calls", "/api/failures",
                 "/api/tasks", "/api/strategies", "/api/patterns",
                 "/api/guidance", "/api/evaluations", "/api/system"):
        code, ct, body = _get(http_server, path)
        assert code == 200, path
        assert "json" in ct, path
        json.loads(body)  # valid JSON


def test_server_static_assets(http_server):
    code, ct, body = _get(http_server, "/")
    assert code == 200 and "html" in ct
    assert b"EBTTO Dashboard" in body
    code, ct, body = _get(http_server, "/app.js")
    assert code == 200 and "javascript" in ct
    code, ct, _ = _get(http_server, "/styles.css")
    assert code == 200 and "css" in ct


def test_server_no_mutation_endpoints(http_server):
    import urllib.error
    for path in ("/api/reset", "/api/mode", "/api/prune", "/api/delete",
                 "/api/replay", "/api/sql"):
        try:
            _get(http_server, path)
            raise AssertionError(f"{path} should not exist")
        except urllib.error.HTTPError as e:
            assert e.code == 404, path


def test_server_rejects_post(http_server):
    import urllib.error
    req = urllib.request.Request(f"http://127.0.0.1:{http_server}/api/tool_calls",
                                 data=b"{}", method="POST")
    try:
        urllib.request.urlopen(req)
        raise AssertionError("POST must not be accepted")
    except urllib.error.HTTPError as e:
        assert e.code in (400, 501)


def test_server_unknown_path_404(http_server):
    import urllib.error
    with pytest.raises(urllib.error.HTTPError) as ei:
        _get(http_server, "/nope")
    assert ei.value.code == 404


def test_server_binds_loopback_only(http_server):
    """The port must not be reachable on a non-loopback local interface."""
    import socket
    host = socket.gethostbyname(socket.gethostname())
    s = socket.socket()
    s.settimeout(1)
    try:
        s.connect((host, http_server))
        raise AssertionError("dashboard reachable off-loopback")
    except (ConnectionRefusedError, socket.timeout, OSError):
        pass
    finally:
        s.close()


# --- XSS ---------------------------------------------------------------------

def test_xss_payloads_are_inert_text(tmp_path):
    """Malicious strings stored in the DB must serialize as JSON strings —
    the frontend renders via textContent, never innerHTML."""
    store = Store(tmp_path)
    from hermes_ebtto import events as ev
    evil = '<script>alert(1)</script><img src=x onerror=alert(2)>'
    store.record_task(ev.Task(task_fingerprint="fp", task_family="terminal",
                              sanitized_intent=evil))
    evil_task = store._execute(
        "SELECT task_id FROM tasks LIMIT 1", commit=False).fetchone()[0]
    store.record_tool_call(ev.ToolCall(task_id=evil_task, turn_id="t",
                                       tool_call_id="c1", tool_name="terminal",
                                       error_message=evil, result_status="error"))
    c = queries.open_ro(str(tmp_path))
    try:
        d = queries.tool_calls(c, window="all")
        assert evil in json.dumps(d)  # stays a JSON string
        det = queries.tool_call_detail(c, "c1")
        assert det["error_message"] == evil
        # JS source never interpolates API data via innerHTML
        js = (Path(server.__file__).parent / "assets" / "app.js").read_text(encoding="utf-8")
        code = js.split("*/", 1)[1]  # strip the leading block comment
        code_lines = [l for l in code.splitlines()
                      if not l.lstrip().startswith("//")]
        assert not any("innerHTML" in l for l in code_lines), \
            "frontend must build DOM with textContent"
    finally:
        c.close()


def test_no_external_resources_in_frontend():
    js = (Path(server.__file__).parent / "assets" / "app.js").read_text(encoding="utf-8")
    html = (Path(server.__file__).parent / "assets" / "index.html").read_text(encoding="utf-8")
    for src in (js + html):
        assert "http://" not in src.replace("http://127.0.0.1", "")
        assert "cdn" not in src.lower()


# --- CLI ---------------------------------------------------------------------

def test_dashboard_cli_entrypoint_importable():
    from hermes_ebtto.dashboard.__main__ import main
    import argparse
    # --help must exit 0 without starting a server
    with pytest.raises(SystemExit) as ei:
        main(["--help"])
    assert ei.value.code == 0


def test_module_launch_help():
    import subprocess, sys
    r = subprocess.run([sys.executable, "-m", "hermes_ebtto.dashboard", "--help"],
                       capture_output=True, text=True, timeout=30)
    assert r.returncode == 0
    assert "dashboard" in r.stdout.lower()
